on:
  schedule:
  - cron: "*/5 * * * *"
  #- cron: "20 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Make and push changes
      run: |
        # git commit -m "daily update"
        # git push -u origin main
        echo "running action"
